name: Test Github Action
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile basic LaTeX document
        uses: ./
        with:
          root_file: codes.tex
          working_directory: /
      - name: Compile basic LaTeX document with lualatex
        uses: ./
        with:
          root_file: codes.tex
          compiler: lualatex
